### ISSUE TITLE
When the caption has Chinese (Japanese, Korean) utf-8 characters, sending the file then the caption will be garbled or give an error.

### ISSUE THREAD

**Issue by siknet** [TheCaduceus/tg-upload#46]
**OS & Platform**
WIN11 21H2  AMD 3900XT / 32G RAM /RTX 3070

**Version**
1.1.4

**Command**
`python tg-upload.py --proxy proxy -p 862520 --api_id xxx --api_hash xxx --phone 8618677332520 -l g:\av --capjson caption1 -c saohuo456 --as_video -d`

**Using Proxy?**
True

**Telegram Profile Type:**
User

**Describe the Bug:**
When the caption has Chinese (Japanese, Korean) utf-8 characters, sending the file will be garbled or give an error.

**⛔Note:**
The temporary solution is: 
modify the code at line 656.
`      with open("caption.json", "r") as caption_json:`
Modify it to 
`      with open("caption.json", "r", encoding='utf-8') as caption_json:`

**Comment by TheCaduceus** [comment]
Thanks for report! I will update it shortly. 👍
